### ISSUE TITLE
Incompatible with module tracer

### ISSUE THREAD

**Issue by septianw** [h2non/nar#129]
I trying to build my project that using npm module tracer, but i always get this error message. I am sure spdx-exceptions were there. 

Here is the error message
Error: Cannot find module 'spdx-exceptions' from '/home/asep/workspace/247/nartest/node_modules/tracer/node_modules/dateformat/node_modules/meow/node_modules/normalize-package-data/node_modules/validate-npm-package-license/node_modules/spdx-expression-parse'

Here is file to reproduce
// file index.js
var log = require('tracer').colorConsole();
log.debug('test');

// file package.json
{
  "name": "nartest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "tracer": "^0.8.3"
  }
}

**Comment by h2non** [comment]
`spdx-exceptions` package has not main module and therefore `nar` is not able to resolve the module path using the [node module lookup algorithm](https://nodejs.org/docs/v0.4.8/api/all.html#all_Together...).

I've added an exception for that package in order to resolve it properly via [resolve-tree](https://github.com/h2non/resolve-tree) module used internally by `nar`.

Try updating `nar` and ensure that `resolve-tree@0.1.7` is installed. 
Then try it again generating the archive.
