### ISSUE TITLE
Optional dependencies revisited

### ISSUE THREAD

**Issue by fred-o** [h2non/nar#133]
As mentioned in a comment in #130, it seems optional dependencies doesn't work quite yet. Running `nar c` (v 0.3.35) on a linux box with this `package.json`

```
{
  "dependencies": {
    "chokidar": "^1.4.3"
  }
}
```

fails with the message
```
Creating archive...
Error: Cannot find module 'fsevents' from '/home/fredrik/test/node_modules/chokidar'
```

**Comment by h2non** [comment]
The optional dependency has been provisioned in node_modules/ tree? If yes, in which path?

**Comment by fred-o** [comment]
It's under `node_modules/chokidar`. 

Forgot to mention that I'm running npm 3.6.0.

**Comment by h2non** [comment]
Will do some tests.

**Comment by h2non** [comment]
Got it. The issue was that `npm`, when installing packages, stores a different `package.json` structure than the original one, adding optional installed dependencies in the `dependencies` map, therefore `resolve-tree` will process them as required runtime dependency. I [did a minor improvement](https://github.com/h2non/resolve-tree/commit/97b25e91fcb0792cbdf8d8d0632a794c284e72f2) in `resolve-tree` to deal with this behavior properly.

Also I've bumped `nar` to `0.3.36`, which uses the latest `resolve-tree` version with the fix. 
Feel free to update `nar`, things should work now.
