### ISSUE TITLE
Is it possible to extract a self-contained tarball?

### ISSUE THREAD

**Issue by SimenB** [h2non/nar#146]
We have a tarball created using ` --executable`. When I download that to another machine, I'd like the user to not have to wait for extraction when it's executed. But if I do `./something.nar extract` I'm unable to make it run using the included node executable.

Am I doing something weird?

Ref finn-no/cdn-uploader#3 if you wanna see how I test it

**Comment by h2non** [comment]
Think about executable `nar` archives as a binary file.

Executable archives are executed by default (which transparently implies a tarball extraction into a temporary folder). If you extract the executable (which is not the default way of using it) you must consume the embedded node.js binary provided in the archive, which would be placed into `.bin` directory, as far as I remember.

Optionally, you customize your package in order to extend the $PATH environment pointing to the embedded `node` binary provided by the archive.

Hope this is helpful.

**Comment by SimenB** [comment]
Hmm, I don't know what I did wrong before, but doing `./cdn-uploader.nar extract && .nar/bin/node index.js` works!

I did find a bug though, if I use `./cdn-uploader.nar extract -o some-dir`, `.nar` is still put in CWD, not into `some-dir`. DO you want a separate issue?

**Comment by h2non** [comment]
Yeah, a separated issue would be great.

**Comment by SimenB** [comment]
Aight, see #148
